# Generated by Django 5.1.7 on 2025-04-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
