# Generated by Django 5.1.7 on 2025-04-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_crimereport_email_crimereport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='is_granted',
            field=models.BooleanField(default=False),
        ),
    ]
