# Generated by Django 5.1.7 on 2025-07-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_crimereport_is_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
