# Generated by Django 5.1.7 on 2026-09-16 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_policestation_latitude_policestation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policestation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
